### ISSUE TITLE
How do you resolve your paths in production

### ISSUE THREAD

**Issue by loic-roux-404** [SoldierCorp/webpack-starter-pug-sass-es6-jquery#1]
I can't build correctly in production mode, the "/" setting in public path seems not work with initial config. My html search a wrong path to css and js bundles.

I try "./" but i can't resolve pictures imported from css.

That's the only tricks i've done for the moment.
In my app.js i do the following import, i also remove url-loader file limit
```
document.addEventListener("DOMContentLoaded" , function(){

  require.context("./assets/images/", true, /\.(png|svg|jpg|gif)$/);

});
```

Please help me i don't understand all webpack things...

EDIT : I think it's cause by my desktop cause your initial project without any changes doesn't find bundles..

**Comment by SoldierCorp** [comment]
Hi @loicroux69!

So, the issue is been fixed in your side?

This starter was tested on Mac, Linux and Windows without any additional requirements but only the ones listed in the readme but still if you have more troubles, just let me know :)

**Comment by loic-roux-404** [comment]
I set the output publicPath :  './' and after i resolve by set the publicPath for each loaders.
I do the following tricks for fonts.

```
        {
          test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
          loader: 'url-loader',
          
          options: {
            publicPath:'../../',
            limit: 5000,
            name: 'assets/fonts/[name].[hash:7].[ext]',
          }
        },
```

**Comment by SoldierCorp** [comment]
That's weird but is good that you could figured out.

Don't hesitate to write more if you have another issue :)
