### ISSUE TITLE
upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9"

### ISSUE THREAD

**Issue by epubreader** [SoldierCorp/webpack-starter-pug-sass-es6-jquery#23]
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "15.3.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

can you resolve it , thanks.

**Comment by SoldierCorp** [comment]
Hi @epubreader,

I'll try to take a look at this in the following days meanwhile, you can do this:

`yarn install  --ignore-engines`
