### ISSUE TITLE
any icons

### ISSUE THREAD

**Issue by Hiiragi0831** [SoldierCorp/webpack-starter-pug-sass-es6-jquery#40]
Notifications are disabled
Reason: DisabledForApplication Please make sure that the app id is set correctly.
Command Line: C:\web\teosofia\node_modules\node-notifier\vendor\snoreToast\snoretoast-x64.exe -pipeName \\.\pipe\notifierPipe-41459ce9-7761-43d4-9c25-e9ce51834ef2 -p C:\web\teosofia\node_modules\webpack-notifier\logo.png -m "Error: ./assets/styles/_app.scss
ModuleBuildError: Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: ~bootstrap-icons.
        on line 17 of src/assets/styles/_app.scss
>> @import \"~bootstrap-icons\";

**Comment by SoldierCorp** [comment]
Hi @Hiiragi0831 !

I just read the documentation and in order to use those icons, you have to import the file into the `app.js` file, like this:

`import 'bootstrap-icons/font/bootstrap-icons.css'`

Then you can use the icon within the template using this:

`i.bi-toggles` or `<i class="bi-toggles"></i>`

**Comment by Hiiragi0831** [comment]
Not working =(
ERROR in ../node_modules/bootstrap-icons/font/bootstrap-icons.css
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'colormin'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, esModule? }
    at validate (C:\web\teosofia\node_modules\schema-utils\dist\validate.js:104:11)
    at Object.loader (C:\web\teosofia\node_modules\css-loader\dist\index.js:36:29)
    at processResult (C:\web\teosofia\node_modules\webpack\lib\NormalModule.js:703:19)
    at C:\web\teosofia\node_modules\webpack\lib\NormalModule.js:809:5
    at C:\web\teosofia\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\web\teosofia\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./app.js 12:0-50

**Comment by SoldierCorp** [comment]
@Hiiragi0831 

Please pull the latest changes, I removed deprecated options of the css-loader.

**Comment by Hiiragi0831** [comment]
Working
