### ISSUE TITLE
mixin image

### ISSUE THREAD

**Issue by Hiiragi0831** [SoldierCorp/webpack-starter-pug-sass-es6-jquery#49]
mixin catalog-item(img)
  img(src=require=img)
  .........

 +catalog-item( 'images/catalog/catalog2-01.png')

does not work, and does not build correctly

but the full link works, but builds incorrectly

 +catalog-item( '/assets/images/catalog/catalog2-01.png')

**Comment by SoldierCorp** [comment]
Hi @Hiiragi0831 !

Here you can see the correct way of using an image within your project.

https://github.com/SoldierCorp/webpack-starter-pug-sass-es6-jquery/blob/e68360e4f76781bd130d7c3d10fbce7382f6f7bb/src/views/components/menu.pug#L5

**Comment by Hiiragi0831** [comment]
https://github.com/Hiiragi0831/demo

Html Webpack Plugin:
  TypeError: pug_mixins.image is not a function
  
  - index.pug:11 template
    [..]/[html-webpack-plugin]/lib/loader.js!./views/index.pug:11:20
  
  - index.js:450 
    [demo]/[html-webpack-plugin]/index.js:450:16
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - async Promise.all

**Comment by Hiiragi0831** [comment]
regular images work well, but if you use them as variables (when you need to create a gallery) and use a mixin, the collector either swears or doesn't see them

**Comment by SoldierCorp** [comment]
@Hiiragi0831 

Alright!

Let me take a look today and I will get back to you.

**Comment by SoldierCorp** [comment]
@Hiiragi0831 

- You forgot to include the mixin in your `index.pug` in order to use it. (Although I recommend you to use a separate file for each mixin.
```
include ./mixins/list.pug
```
- Change the line where you are trying to use the image, for this one:
```
+image(require('images/image.png'))
```

**Comment by Hiiragi0831** [comment]
Thanks, maybe add this to readme?
