### ISSUE TITLE
vendor.XXXX.bundle.js big size

### ISSUE THREAD

**Issue by Hiiragi0831** [SoldierCorp/webpack-starter-pug-sass-es6-jquery#50]
Empty project weighs 808KiB

**Comment by SoldierCorp** [comment]
Hi @Hiiragi0831 

jQuery is the responsible in this case, if you are not using it just remove it and the size will importantly decrease.

**Comment by Hiiragi0831** [comment]
Thanks for the answer, I did not think that jQuery has such a large size
