### ISSUE TITLE
Is there a way to automate adding new pug pages to webpack?

### ISSUE THREAD

**Issue by ekfuhrmann** [SoldierCorp/webpack-starter-pug-sass-es6-jquery#51]
This is a really nice starter file that mimics a lot of what I'm trying to do; however, coming from a [similar Gulp boilerplate](https://github.com/ekfuhrmann/project-boilerplate) I've been using, I can't quite figure out how to properly account for new pug pages within the project. It seems like if I am to add/remove a new page, I need to rebuild webpack each time. Is there any way to automate this process? Adding `watch: true,` to webpack doesn't seem to solve for the problem.

**Comment by SoldierCorp** [comment]
Hi @ekfuhrmann !

I'll take a look at it later today.

**Comment by ekfuhrmann** [comment]
No rush, just curious if it's possible to have webpack watch for added/removed pug files and just hot update without a rebuild.
